name: Deploy to VPS

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # Important: fetch-depth: 0 si vous avez besoin de l'historique, sinon par défaut c'est 1

    - name: Déployer les fichiers sur le VPS via rsync
      uses: webfactory/rsync-deploy@v0.8.0
      with:
        deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_host: ${{ secrets.SSH_VPS_IP }}
        remote_user: ${{ secrets.SSH_VPS_USER }}
        remote_port: ${{ secrets.SSH_VPS_PORT }}
        remote_path: /var/www/liste-rgesn/
        local_path: ./
        rsync_args: -avz --delete