name: Deploy to VPS

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Déployer sur le VPS via SSH
      uses: appleboy/ssh-action@v1
      with:
        IP: ${{ secrets.SSH_VPS_IP }}
        USER: ${{ secrets.SSH_VPS_USER }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PORT: ${{ secrets.SSH_VPS_PORT }}
        script: |
          cd /var/www/liste-rgesn
          git pull origin main
          # npm ci --production
          # pm2 restart monapp